name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag awesome-days:$(date +'%y%m.%d%H')
        docker tag awesome-days:$(date +'%y%m.%d%H') psih747/awesome-days:$(date +'%y%m.%d%H')
        docker tag awesome-days:$(date +'%y%m.%d%H') psih747/awesome-days:latest
        docker push
